### PR TITLE
Create arithmetic_arranger

### PR DESCRIPTION
**Pull request by Wiz-2**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)

Closes #XXXXX

### CODE REVIEW

**Comment by Wiz-2** [comment]
Grant me permission to merge

**Comment by Wiz-2** [comment]
Grant me permission to merge

**Comment by Wiz-2** [comment]
grant me permission to merge

**Comment by gikf** [comment]
Hey @Wiz-2 

Looks like you were trying to open PR to your own fork at https://github.com/Wiz-2/boilerplate-arithmetic-formatter, not the original https://github.com/freeCodeCamp/boilerplate-arithmetic-formatter boilerplate repository.

This is a standard message notifying you that we've reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding.

**Pull request closed without merging**
