### PR TITLE
fix testcase test_too_many_problems without any problem

### PR DESCRIPTION
**Pull request by DLT1412**
fix testcase test_too_many_problems but do not have any problem

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)

Closes #XXXXX

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Hi @DLT1412, could you go into a bit more detail about why you think this change is necessary?

**Comment by DLT1412** [comment]
> Hi @DLT1412, could you go into a bit more detail about why you think this change is necessary?

Testcase `test_too_many_problems` expect with `"Error: Too many problems."` return, but input not violate any rule at https://github.com/freeCodeCamp/boilerplate-arithmetic-formatter#rules, so I change the input to make this test make sense.

**Comment by gikf** [comment]
Hey @DLT1412

Thank you for opening this pull request.

This test case is violating first rule - it supplies list with `6` problems, while allowed limit is five. 

This is a standard message notifying you that we've reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding.

**Comment by DLT1412** [comment]
Thanks, sorry for my misunderstanding.

**Pull request closed without merging**
